project:
  type: website

website:
  title: "Steven Wang"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: nbasalaries/nbasalaries.qmd
        text: NBA
      - href: geospatial/geospatial.qmd
        text: Geospatial

format:
  html:
    theme: 
      light: spacelab
      dark: cyborg
    css: styles.css
    respect-user-color-scheme: true
    toc: true